// Lab 05 - gRPC Calculator Service Definition
// This .proto file defines the service interface.
// protoc generates the Go client and server code automatically.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: calculator.proto

package calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"` // "add", "subtract", "multiply", "divide"
	A             float64                `protobuf:"fixed64,2,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,3,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRequest) Reset() {
	*x = CalcRequest{}
	mi := &file_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest) ProtoMessage() {}

func (x *CalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest.ProtoReflect.Descriptor instead.
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalcRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CalcRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *CalcRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

type CalcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcResponse) Reset() {
	*x = CalcResponse{}
	mi := &file_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcResponse) ProtoMessage() {}

func (x *CalcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcResponse.ProtoReflect.Descriptor instead.
func (*CalcResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalcResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CalcResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FibRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // How many Fibonacci numbers to generate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibRequest) Reset() {
	*x = FibRequest{}
	mi := &file_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibRequest) ProtoMessage() {}

func (x *FibRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibRequest.ProtoReflect.Descriptor instead.
func (*FibRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *FibRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FibResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibResponse) Reset() {
	*x = FibResponse{}
	mi := &file_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibResponse) ProtoMessage() {}

func (x *FibResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibResponse.ProtoReflect.Descriptor instead.
func (*FibResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *FibResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *FibResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\n" +
	"calculator\"G\n" +
	"\vCalcRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\f\n" +
	"\x01a\x18\x02 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x03 \x01(\x01R\x01b\"<\n" +
	"\fCalcResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\"\n" +
	"\n" +
	"FibRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"9\n" +
	"\vFibResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index2\x92\x01\n" +
	"\n" +
	"Calculator\x12>\n" +
	"\tCalculate\x12\x17.calculator.CalcRequest\x1a\x18.calculator.CalcResponse\x12D\n" +
	"\x0fFibonacciStream\x12\x16.calculator.FibRequest\x1a\x17.calculator.FibResponse0\x01B\x16Z\x14lab05grpc/calculatorb\x06proto3"

var (
	file_calculator_proto_rawDescOnce sync.Once
	file_calculator_proto_rawDescData []byte
)

func file_calculator_proto_rawDescGZIP() []byte {
	file_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)))
	})
	return file_calculator_proto_rawDescData
}

var file_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calculator_proto_goTypes = []any{
	(*CalcRequest)(nil),  // 0: calculator.CalcRequest
	(*CalcResponse)(nil), // 1: calculator.CalcResponse
	(*FibRequest)(nil),   // 2: calculator.FibRequest
	(*FibResponse)(nil),  // 3: calculator.FibResponse
}
var file_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.Calculator.Calculate:input_type -> calculator.CalcRequest
	2, // 1: calculator.Calculator.FibonacciStream:input_type -> calculator.FibRequest
	1, // 2: calculator.Calculator.Calculate:output_type -> calculator.CalcResponse
	3, // 3: calculator.Calculator.FibonacciStream:output_type -> calculator.FibResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_proto_msgTypes,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
